// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: sitesurveypb/sitesurvey.proto

package sitesurveypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SurveyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SurveyRequest) Reset() {
	*x = SurveyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sitesurveypb_sitesurvey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyRequest) ProtoMessage() {}

func (x *SurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sitesurveypb_sitesurvey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyRequest.ProtoReflect.Descriptor instead.
func (*SurveyRequest) Descriptor() ([]byte, []int) {
	return file_sitesurveypb_sitesurvey_proto_rawDescGZIP(), []int{0}
}

type SurveyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receive []*OneReceive `protobuf:"bytes,1,rep,name=receive,proto3" json:"receive,omitempty"`
}

func (x *SurveyReply) Reset() {
	*x = SurveyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sitesurveypb_sitesurvey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SurveyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyReply) ProtoMessage() {}

func (x *SurveyReply) ProtoReflect() protoreflect.Message {
	mi := &file_sitesurveypb_sitesurvey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyReply.ProtoReflect.Descriptor instead.
func (*SurveyReply) Descriptor() ([]byte, []int) {
	return file_sitesurveypb_sitesurvey_proto_rawDescGZIP(), []int{1}
}

func (x *SurveyReply) GetReceive() []*OneReceive {
	if x != nil {
		return x.Receive
	}
	return nil
}

type OneReceive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body  string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *OneReceive) Reset() {
	*x = OneReceive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sitesurveypb_sitesurvey_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneReceive) ProtoMessage() {}

func (x *OneReceive) ProtoReflect() protoreflect.Message {
	mi := &file_sitesurveypb_sitesurvey_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneReceive.ProtoReflect.Descriptor instead.
func (*OneReceive) Descriptor() ([]byte, []int) {
	return file_sitesurveypb_sitesurvey_proto_rawDescGZIP(), []int{2}
}

func (x *OneReceive) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *OneReceive) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sitesurveypb_sitesurvey_proto protoreflect.FileDescriptor

var file_sitesurveypb_sitesurvey_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x69, 0x74, 0x65, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x70, 0x62, 0x2f, 0x73,
	0x69, 0x74, 0x65, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x73, 0x69, 0x74, 0x65, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x53,
	0x75, 0x72, 0x76, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x0b,
	0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x07, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73,
	0x69, 0x74, 0x65, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x2e, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x22, 0x36, 0x0a,
	0x0a, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x4c, 0x0a, 0x06, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x12,
	0x42, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x12, 0x19, 0x2e,
	0x73, 0x69, 0x74, 0x65, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x2e, 0x53, 0x75, 0x72, 0x76, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x73,
	0x75, 0x72, 0x76, 0x65, 0x79, 0x2e, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x73, 0x75, 0x72,
	0x76, 0x65, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sitesurveypb_sitesurvey_proto_rawDescOnce sync.Once
	file_sitesurveypb_sitesurvey_proto_rawDescData = file_sitesurveypb_sitesurvey_proto_rawDesc
)

func file_sitesurveypb_sitesurvey_proto_rawDescGZIP() []byte {
	file_sitesurveypb_sitesurvey_proto_rawDescOnce.Do(func() {
		file_sitesurveypb_sitesurvey_proto_rawDescData = protoimpl.X.CompressGZIP(file_sitesurveypb_sitesurvey_proto_rawDescData)
	})
	return file_sitesurveypb_sitesurvey_proto_rawDescData
}

var file_sitesurveypb_sitesurvey_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sitesurveypb_sitesurvey_proto_goTypes = []interface{}{
	(*SurveyRequest)(nil), // 0: sitesurvey.SurveyRequest
	(*SurveyReply)(nil),   // 1: sitesurvey.SurveyReply
	(*OneReceive)(nil),    // 2: sitesurvey.OneReceive
}
var file_sitesurveypb_sitesurvey_proto_depIdxs = []int32{
	2, // 0: sitesurvey.SurveyReply.receive:type_name -> sitesurvey.OneReceive
	0, // 1: sitesurvey.Survey.SendSurvey:input_type -> sitesurvey.SurveyRequest
	1, // 2: sitesurvey.Survey.SendSurvey:output_type -> sitesurvey.SurveyReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sitesurveypb_sitesurvey_proto_init() }
func file_sitesurveypb_sitesurvey_proto_init() {
	if File_sitesurveypb_sitesurvey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sitesurveypb_sitesurvey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SurveyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sitesurveypb_sitesurvey_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SurveyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sitesurveypb_sitesurvey_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneReceive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sitesurveypb_sitesurvey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sitesurveypb_sitesurvey_proto_goTypes,
		DependencyIndexes: file_sitesurveypb_sitesurvey_proto_depIdxs,
		MessageInfos:      file_sitesurveypb_sitesurvey_proto_msgTypes,
	}.Build()
	File_sitesurveypb_sitesurvey_proto = out.File
	file_sitesurveypb_sitesurvey_proto_rawDesc = nil
	file_sitesurveypb_sitesurvey_proto_goTypes = nil
	file_sitesurveypb_sitesurvey_proto_depIdxs = nil
}
